const BIKES = [
  {
    id: 1,
    name: "Aero Pro Carbon 9",
    brand: "Trek",
    category: "road",
    price: 3299,
    salePrice: null,
    rating: 4.8,
    reviewCount: 124,
    colors: ["#1a1a2e", "#c0392b", "#2c3e50", "#ffffff"],
    colorNames: ["Midnight Black", "Race Red", "Steel Blue", "Pearl White"],
    sizes: ["XS (48cm)", "S (52cm)", "M (54cm)", "L (56cm)", "XL (58cm)", "XXL (61cm)"],
    description: "The Aero Pro Carbon 9 is built for speed-hungry racers who refuse to compromise. An ultralight carbon frame pairs with a precision drivetrain for a ride that's as thrilling as it is fast. Whether you're chasing a personal best or the finish line, this bike delivers.",
    specs: {
      frame: "OCLV Mountain Carbon, 120mm travel",
      fork: "Trek IsoSpeed Carbon",
      gears: "Shimano Ultegra 11-speed",
      brakes: "Shimano Ultegra hydraulic disc",
      weight: "7.4 kg",
      wheelSize: "700c",
      material: "Carbon Fiber",
      suspension: "Full rigid"
    },
    stock: 8,
    isNew: false,
    isFeatured: true,
    tags: ["race", "carbon", "lightweight", "pro"],
    images: ["road", "road2", "road3"]
  },
  {
    id: 2,
    name: "Stumpjumper EVO Elite",
    brand: "Specialized",
    category: "mountain",
    price: 2799,
    salePrice: 2499,
    rating: 4.9,
    reviewCount: 89,
    colors: ["#2d6a4f", "#e63946", "#023e8a", "#f4a261"],
    colorNames: ["Forest Green", "Crimson", "Ocean Blue", "Sunset Orange"],
    sizes: ["S (15\")", "M (17\")", "L (19\")", "XL (21\")"],
    description: "Designed for the trails that push your limits, the Stumpjumper EVO Elite is your ultimate mountain companion. With 150mm of travel and precise geometry, it handles technical terrain with confidence while remaining playful on the flowy stuff.",
    specs: {
      frame: "FACT 11m Carbon, 150mm travel",
      fork: "RockShox Pike Ultimate, 150mm",
      gears: "SRAM GX Eagle 12-speed",
      brakes: "SRAM Level TL hydraulic disc",
      weight: "12.1 kg",
      wheelSize: "29\"",
      material: "Carbon Fiber",
      suspension: "Full suspension"
    },
    stock: 3,
    isNew: true,
    isFeatured: true,
    tags: ["trail", "mtb", "enduro", "carbon"],
    images: ["mountain", "mountain2", "mountain3"]
  },
  {
    id: 3,
    name: "Gazelle Ultimate C380+",
    brand: "Gazelle",
    category: "electric",
    price: 3899,
    salePrice: null,
    rating: 4.7,
    reviewCount: 203,
    colors: ["#2b2d42", "#8d99ae", "#ef233c", "#06d6a0"],
    colorNames: ["Anthracite", "Silver Storm", "Dutch Red", "Mint"],
    sizes: ["S (46cm)", "M (53cm)", "L (57cm)", "XL (61cm)"],
    description: "The Gazelle Ultimate C380+ redefines electric cycling. With Bosch Performance Line motor and a smooth 380Wh battery hidden in the frame, you get up to 130km of range. Perfect for commuters who want to arrive fresh — every single day.",
    specs: {
      frame: "Premium Aluminum, integrated battery",
      fork: "Suntour NCX D-LO suspension fork",
      gears: "Shimano Nexus 8-speed automatic",
      brakes: "Shimano hydraulic disc brakes",
      weight: "23.5 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      motor: "Bosch Performance Line 85Nm",
      battery: "Bosch PowerTube 380Wh",
      range: "Up to 130km"
    },
    stock: 12,
    isNew: false,
    isFeatured: true,
    tags: ["electric", "commuter", "bosch", "city"],
    images: ["electric", "electric2", "electric3"]
  },
  {
    id: 4,
    name: "Batavus Dinsdag E-Go",
    brand: "Batavus",
    category: "electric",
    price: 2199,
    salePrice: 1999,
    rating: 4.5,
    reviewCount: 311,
    colors: ["#264653", "#e9c46a", "#f4a261", "#264653"],
    colorNames: ["Deep Sea", "Golden Sand", "Terracotta", "Midnight"],
    sizes: ["S (46cm)", "M (50cm)", "L (55cm)"],
    description: "Urban mobility made effortless. The Batavus Dinsdag E-Go brings classic Dutch design into the electric age. The integrated Bafang motor provides smooth, silent assistance up to 25 km/h, making every ride a pleasure.",
    specs: {
      frame: "Dutch Step-Through Aluminum",
      fork: "Rigid alloy",
      gears: "Shimano Nexus 7-speed",
      brakes: "Hydraulic rim brakes",
      weight: "21 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      motor: "Bafang 36V 250W",
      battery: "36V 13.4Ah (480Wh)",
      range: "Up to 100km"
    },
    stock: 18,
    isNew: false,
    isFeatured: false,
    tags: ["electric", "dutch", "step-through", "city"],
    images: ["city", "city2", "city3"]
  },
  {
    id: 5,
    name: "Synapse Carbon 105",
    brand: "Cannondale",
    category: "road",
    price: 1999,
    salePrice: null,
    rating: 4.6,
    reviewCount: 76,
    colors: ["#3a86ff", "#ff006e", "#8338ec", "#fb5607"],
    colorNames: ["Speed Blue", "Hot Pink", "Ultraviolet", "Blaze Orange"],
    sizes: ["XS (44cm)", "S (48cm)", "M (51cm)", "L (54cm)", "XL (57cm)"],
    description: "The Synapse Carbon 105 is the endurance road bike you've been waiting for. SmartForm C1 Premium Alloy construction meets Shimano 105 11-speed precision. Comfortable enough for century rides, fast enough for your local crit.",
    specs: {
      frame: "SmartForm C1 Premium Alloy",
      fork: "SAVE carbon, full composite",
      gears: "Shimano 105 11-speed",
      brakes: "Shimano 105 hydraulic disc",
      weight: "8.9 kg",
      wheelSize: "700c",
      material: "Alloy/Carbon Fork",
      suspension: "Rigid"
    },
    stock: 6,
    isNew: true,
    isFeatured: false,
    tags: ["endurance", "road", "105", "alloy"],
    images: ["road", "road3", "road2"]
  },
  {
    id: 6,
    name: "Talon 29 3",
    brand: "Giant",
    category: "mountain",
    price: 899,
    salePrice: 749,
    rating: 4.3,
    reviewCount: 445,
    colors: ["#06d6a0", "#ef476f", "#ffd166", "#073b4c"],
    colorNames: ["Teal Metallic", "Berry Red", "Bright Yellow", "Dark Slate"],
    sizes: ["S (15\")", "M (17\")", "L (19\")", "XL (21\")"],
    description: "Entry-level doesn't mean entry-performance. The Giant Talon 29 3 delivers capable trail performance at an accessible price. Lightweight ALUXX aluminum frame and 100mm suspension fork make short work of weekend trails.",
    specs: {
      frame: "ALUXX-Grade Aluminum",
      fork: "SR Suntour XCT, 100mm travel",
      gears: "Shimano Acera 3x8, 24-speed",
      brakes: "Tektro hydraulic disc",
      weight: "13.8 kg",
      wheelSize: "29\"",
      material: "Aluminum",
      suspension: "Hardtail"
    },
    stock: 25,
    isNew: false,
    isFeatured: false,
    tags: ["entry", "hardtail", "trail", "value"],
    images: ["mountain", "mountain3", "mountain2"]
  },
  {
    id: 7,
    name: "Scott Addict RC 30",
    brand: "Scott",
    category: "road",
    price: 2499,
    salePrice: null,
    rating: 4.7,
    reviewCount: 58,
    colors: ["#ffffff", "#000000", "#c9184a", "#0077b6"],
    colorNames: ["Gloss White", "Stealth Black", "Carmine", "Pacific Blue"],
    sizes: ["XS (49cm)", "S (52cm)", "M (54cm)", "L (56cm)", "XL (58cm)"],
    description: "Born from the WorldTour, brought to the masses. The Scott Addict RC 30 features HMF carbon layup technology delivering the stiffness-to-weight ratio that pros demand. Shimano 105 Di2 electronic shifting takes your performance to the next level.",
    specs: {
      frame: "Scott HMF Carbon",
      fork: "Scott Addict HMF Full Carbon",
      gears: "Shimano 105 Di2 12-speed electronic",
      brakes: "Shimano 105 Di2 hydraulic disc",
      weight: "7.8 kg",
      wheelSize: "700c",
      material: "Carbon Fiber",
      suspension: "Rigid"
    },
    stock: 4,
    isNew: true,
    isFeatured: true,
    tags: ["worldtour", "di2", "electronic", "carbon"],
    images: ["road2", "road", "road3"]
  },
  {
    id: 8,
    name: "Cube Kathmandu Hybrid Pro 625",
    brand: "Cube",
    category: "electric",
    price: 2899,
    salePrice: null,
    rating: 4.6,
    reviewCount: 167,
    colors: ["#1b263b", "#415a77", "#e63946", "#2d6a4f"],
    colorNames: ["Dark Night", "Steel", "Red Alert", "Alpine Green"],
    sizes: ["S (46cm)", "M (50cm)", "L (54cm)", "XL (58cm)"],
    description: "Adventure meets electric power. The Cube Kathmandu Hybrid Pro 625 is a versatile e-bike that thrives on long-distance tours. The Bosch Performance CX motor combined with a massive 625Wh battery ensures you'll never run out of power on those epic adventures.",
    specs: {
      frame: "Cube AL Road, double butted aluminum",
      fork: "Suntour NEX E25 suspension fork",
      gears: "Shimano Deore 1x10-speed",
      brakes: "Shimano MT201 hydraulic disc",
      weight: "24.2 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      motor: "Bosch Performance CX 85Nm",
      battery: "Bosch PowerTube 625Wh",
      range: "Up to 170km"
    },
    stock: 7,
    isNew: false,
    isFeatured: true,
    tags: ["touring", "electric", "adventure", "bosch"],
    images: ["electric2", "electric", "electric3"]
  },
  {
    id: 9,
    name: "Procaliber 9.6",
    brand: "Trek",
    category: "mountain",
    price: 1799,
    salePrice: 1599,
    rating: 4.5,
    reviewCount: 92,
    colors: ["#ff6b35", "#004e89", "#1a936f", "#c9cba3"],
    colorNames: ["Burnt Orange", "Deep Navy", "Sage", "Champagne"],
    sizes: ["S (15.5\")", "M (17.5\")", "L (19.5\")", "XL (21.5\")"],
    description: "Cross-country speed meets trail confidence. The Trek Procaliber 9.6 is the hardtail for riders who want to go fast and far. Alpha Platinum Aluminum frame keeps weight down while Shimano Deore 1x11 keeps shifting smooth.",
    specs: {
      frame: "Alpha Platinum Aluminum",
      fork: "Fox Rhythm 32 Float, 100mm",
      gears: "Shimano Deore 1x11-speed",
      brakes: "Shimano MT200 hydraulic disc",
      weight: "11.2 kg",
      wheelSize: "29\"",
      material: "Aluminum",
      suspension: "Hardtail"
    },
    stock: 10,
    isNew: false,
    isFeatured: false,
    tags: ["xc", "hardtail", "cross-country", "speed"],
    images: ["mountain2", "mountain", "mountain3"]
  },
  {
    id: 10,
    name: "Sirrus 3.0",
    brand: "Specialized",
    category: "city",
    price: 1199,
    salePrice: null,
    rating: 4.4,
    reviewCount: 278,
    colors: ["#606c38", "#283618", "#dda15e", "#bc6c25"],
    colorNames: ["Fern Green", "Dark Olive", "Wheat", "Rust"],
    sizes: ["XS (44cm)", "S (48cm)", "M (52cm)", "L (56cm)", "XL (61cm)"],
    description: "The Sirrus 3.0 blurs the line between fitness and fun. Lightweight A1 Premium Aluminum frame and a flat bar make it nimble in traffic while staying comfortable on longer rides. Perfect for the rider who wants to do it all.",
    specs: {
      frame: "A1 Premium Aluminum",
      fork: "Specialized FACT carbon fiber",
      gears: "Shimano Tiagra 2x10-speed",
      brakes: "TRP Spyre hydraulic disc",
      weight: "9.4 kg",
      wheelSize: "700c",
      material: "Aluminum",
      suspension: "Rigid"
    },
    stock: 15,
    isNew: false,
    isFeatured: false,
    tags: ["fitness", "commuter", "flat-bar", "versatile"],
    images: ["city", "city3", "city2"]
  },
  {
    id: 11,
    name: "Gazelle Medeo T9 HMB",
    brand: "Gazelle",
    category: "city",
    price: 1099,
    salePrice: null,
    rating: 4.6,
    reviewCount: 189,
    colors: ["#3d405b", "#81b29a", "#f2cc8f", "#e07a5f"],
    colorNames: ["Twilight Purple", "Sea Glass", "Vanilla", "Terracotta"],
    sizes: ["S (46cm)", "M (53cm)", "L (57cm)"],
    description: "The perfect Dutch city bike. The Gazelle Medeo T9 HMB combines classic design with modern reliability. Integrated lights, a rear rack, and fenders make it ready for daily use straight out of the box. 9-speed Shimano gearing handles any hill.",
    specs: {
      frame: "High-tensile aluminum Dutch design",
      fork: "Rigid steel",
      gears: "Shimano Nexus 9-speed",
      brakes: "Shimano hydraulic disc",
      weight: "16.2 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      extras: "Integrated lights, rear rack, fenders"
    },
    stock: 22,
    isNew: false,
    isFeatured: false,
    tags: ["dutch", "city", "commuter", "practical"],
    images: ["city2", "city", "city3"]
  },
  {
    id: 12,
    name: "Emonda ALR 4",
    brand: "Trek",
    category: "road",
    price: 1499,
    salePrice: 1299,
    rating: 4.5,
    reviewCount: 103,
    colors: ["#ff595e", "#ffca3a", "#6a4c93", "#1982c4"],
    colorNames: ["Viper Red", "Lemon Drop", "Royal Purple", "Cobalt"],
    sizes: ["XS (44cm)", "S (50cm)", "M (54cm)", "L (56cm)", "XL (60cm)"],
    description: "Light. Climby. Fast. The Trek Emonda ALR 4 is the climber's dream at an accessible price point. Alpha Platinum Aluminum construction delivers a ride quality that punches well above its weight class. Shimano 105 drivetrain keeps things honest.",
    specs: {
      frame: "Alpha Platinum Aluminum",
      fork: "Trek IsoSpeed Carbon",
      gears: "Shimano 105 2x11-speed",
      brakes: "Shimano 105 hydraulic disc",
      weight: "8.5 kg",
      wheelSize: "700c",
      material: "Aluminum/Carbon Fork",
      suspension: "Rigid"
    },
    stock: 9,
    isNew: false,
    isFeatured: false,
    tags: ["climbing", "lightweight", "road", "value"],
    images: ["road3", "road", "road2"]
  },
  {
    id: 13,
    name: "Cube Aim Pro",
    brand: "Cube",
    category: "mountain",
    price: 649,
    salePrice: null,
    rating: 4.2,
    reviewCount: 387,
    colors: ["#073b4c", "#118ab2", "#06d6a0", "#ffd166"],
    colorNames: ["Dark Ocean", "Sky Blue", "Mint Green", "Solar Yellow"],
    sizes: ["S (14\")", "M (16\")", "L (18\")", "XL (20\")"],
    description: "The Cube Aim Pro is your gateway to mountain biking. Built tough with a double-butted aluminum frame and reliable Shimano groupset, it's the hardtail that'll have you grinning on every trail without breaking the bank.",
    specs: {
      frame: "Cube Aluminium 6061, double butted",
      fork: "SR Suntour XCT, 100mm travel",
      gears: "Shimano Acera 3x8, 24-speed",
      brakes: "Shimano M315 hydraulic disc",
      weight: "14.1 kg",
      wheelSize: "29\"",
      material: "Aluminum",
      suspension: "Hardtail"
    },
    stock: 30,
    isNew: false,
    isFeatured: false,
    tags: ["entry", "beginner", "hardtail", "value"],
    images: ["mountain3", "mountain", "mountain2"]
  },
  {
    id: 14,
    name: "Batavus Razer Speed 8",
    brand: "Batavus",
    category: "city",
    price: 799,
    salePrice: null,
    rating: 4.3,
    reviewCount: 156,
    colors: ["#22223b", "#4a4e69", "#9a8c98", "#c9ada7"],
    colorNames: ["Midnight", "Dusk", "Mauve", "Blush"],
    sizes: ["S (46cm)", "M (50cm)", "L (54cm)", "XL (58cm)"],
    description: "Speed meets Dutch practicality. The Batavus Razer Speed 8 is built for the urban warrior who won't compromise on style or performance. 8-speed Shimano gearing and hydraulic disc brakes make city riding a breeze in any weather.",
    specs: {
      frame: "Urban Alloy Speed Geometry",
      fork: "Rigid alloy",
      gears: "Shimano Altus 8-speed",
      brakes: "Hydraulic disc brakes",
      weight: "14.5 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      extras: "Integrated rear rack"
    },
    stock: 14,
    isNew: true,
    isFeatured: false,
    tags: ["urban", "speed", "dutch", "practical"],
    images: ["city3", "city", "city2"]
  },
  {
    id: 15,
    name: "Tarmac SL7 Pro",
    brand: "Specialized",
    category: "road",
    price: 4999,
    salePrice: null,
    rating: 4.9,
    reviewCount: 42,
    colors: ["#ffffff", "#000000", "#0077b6", "#c1121f"],
    colorNames: ["Gloss White", "Carbon Black", "Azure", "Race Red"],
    sizes: ["44cm", "49cm", "52cm", "54cm", "56cm", "58cm", "61cm"],
    description: "The Tarmac SL7 Pro is what happens when WorldTour engineering meets real-world performance. FACT 10r carbon fiber, Shimano Ultegra Di2 electronic shifting, and aero integration make this the bike that does everything, faster.",
    specs: {
      frame: "Specialized FACT 10r Carbon",
      fork: "Specialized FACT Carbon",
      gears: "Shimano Ultegra Di2 2x12-speed electronic",
      brakes: "Shimano Ultegra Di2 hydraulic disc",
      weight: "6.8 kg",
      wheelSize: "700c",
      material: "Carbon Fiber",
      suspension: "Rigid"
    },
    stock: 2,
    isNew: true,
    isFeatured: true,
    tags: ["pro", "aero", "di2", "worldtour", "premium"],
    images: ["road", "road2", "road3"]
  },
  {
    id: 16,
    name: "Avail Advanced 1",
    brand: "Giant",
    category: "road",
    price: 2299,
    salePrice: null,
    rating: 4.6,
    reviewCount: 67,
    colors: ["#e76f51", "#264653", "#2a9d8f", "#e9c46a"],
    colorNames: ["Coral", "Charcoal", "Teal", "Gold"],
    sizes: ["XS (43cm)", "S (47cm)", "M (50cm)", "L (52cm)"],
    description: "Designed specifically for women who love to ride fast and far. The Giant Avail Advanced 1 features Advanced-grade composite technology with women-specific geometry for optimal comfort and power transfer. Shimano 105 Di2 is the cherry on top.",
    specs: {
      frame: "Advanced Composite Technology",
      fork: "Advanced Composite",
      gears: "Shimano 105 Di2 2x12-speed",
      brakes: "Shimano 105 Di2 hydraulic disc",
      weight: "8.1 kg",
      wheelSize: "700c",
      material: "Carbon Fiber",
      suspension: "Rigid"
    },
    stock: 5,
    isNew: false,
    isFeatured: false,
    tags: ["women", "endurance", "carbon", "di2"],
    images: ["road2", "road3", "road"]
  },
  {
    id: 17,
    name: "Cube Stereo Hybrid 120",
    brand: "Cube",
    category: "electric",
    price: 3499,
    salePrice: 3199,
    rating: 4.7,
    reviewCount: 95,
    colors: ["#ff6b6b", "#4ecdc4", "#45b7d1", "#96ceb4"],
    colorNames: ["Crimson Flash", "Turquoise", "Sky Ride", "Sage"],
    sizes: ["S (14\")", "M (17\")", "L (19\")", "XL (21\")"],
    description: "Electric mountain biking taken to new heights. The Cube Stereo Hybrid 120 Pro brings Bosch Performance CX power to a full-suspension trail bike. 120mm travel front and rear, SRAM SX Eagle 12-speed, and a 625Wh battery for all-day adventures.",
    specs: {
      frame: "Cube C:62 Carbon, 120mm travel",
      fork: "RockShox 35 Gold RL, 120mm",
      gears: "SRAM SX Eagle 1x12-speed",
      brakes: "Shimano MT420 hydraulic disc",
      weight: "22.3 kg",
      wheelSize: "29\"",
      material: "Carbon Fiber",
      motor: "Bosch Performance CX 85Nm",
      battery: "Bosch PowerTube 625Wh",
      range: "Up to 120km"
    },
    stock: 6,
    isNew: true,
    isFeatured: true,
    tags: ["e-mtb", "electric", "trail", "full-suspension"],
    images: ["electric3", "electric", "electric2"]
  },
  {
    id: 18,
    name: "Spark Kids 20",
    brand: "Scott",
    category: "kids",
    price: 449,
    salePrice: 399,
    rating: 4.4,
    reviewCount: 234,
    colors: ["#ff9f1c", "#2ec4b6", "#e71d36", "#011627"],
    colorNames: ["Sunny Orange", "Aqua", "Firetruck Red", "Deep Space"],
    sizes: ["One Size (20\" wheel)"],
    description: "Give them the ride that sparks a lifelong love of cycling. The Scott Spark Kids 20 features a lightweight aluminum frame scaled perfectly for riders 6-9 years old. Easy-to-use brakes, smooth 7-speed shifting, and color-matched accessories make every ride an adventure.",
    specs: {
      frame: "Lightweight 6061 Aluminum",
      fork: "SR Suntour rigid",
      gears: "Shimano Tourney 7-speed",
      brakes: "Mechanical disc brakes",
      weight: "8.9 kg",
      wheelSize: "20\"",
      material: "Aluminum",
      ageRange: "6-9 years"
    },
    stock: 20,
    isNew: false,
    isFeatured: false,
    tags: ["kids", "youth", "beginner", "fun"],
    images: ["kids", "kids2", "kids3"]
  },
  {
    id: 19,
    name: "Precaliber 24 Speed",
    brand: "Trek",
    category: "kids",
    price: 549,
    salePrice: null,
    rating: 4.5,
    reviewCount: 178,
    colors: ["#7400b8", "#6930c3", "#4ea8de", "#48cae4"],
    colorNames: ["Cosmic Purple", "Violet", "Powder Blue", "Sky"],
    sizes: ["One Size (24\" wheel)"],
    description: "The Precaliber 24 Speed is the next step in a young cyclist's journey. Designed for riders aged 8-12, it features a lightweight aluminum frame, 8-speed gearing, and hydraulic disc brakes — serious components that grow with serious young riders.",
    specs: {
      frame: "Alpha Silver Aluminum",
      fork: "SR Suntour M3030, 50mm travel",
      gears: "Shimano Altus 1x8-speed",
      brakes: "Tektro hydraulic disc",
      weight: "10.2 kg",
      wheelSize: "24\"",
      material: "Aluminum",
      ageRange: "8-12 years"
    },
    stock: 15,
    isNew: false,
    isFeatured: false,
    tags: ["kids", "youth", "8-12", "quality"],
    images: ["kids2", "kids", "kids3"]
  },
  {
    id: 20,
    name: "Gazelle CityZen C380+ HMB",
    brand: "Gazelle",
    category: "electric",
    price: 4299,
    salePrice: null,
    rating: 4.8,
    reviewCount: 87,
    colors: ["#2b2d42", "#8d99ae", "#ef233c", "#06d6a0"],
    colorNames: ["Matte Black", "Storm Grey", "Dutch Red", "Electric Mint"],
    sizes: ["S (46cm)", "M (53cm)", "L (57cm)", "XL (61cm)"],
    description: "The pinnacle of Dutch e-bike engineering. The Gazelle CityZen C380+ HMB is for those who refuse to settle. Integrated Bosch motor and battery in a sleek aluminum frame, hydraulic disc brakes, and connectivity via the Bosch eBike Flow app make this a smart machine for smart commuters.",
    specs: {
      frame: "Aluminum, fully integrated battery",
      fork: "Suspension fork with lockout",
      gears: "Enviolo Automatiq CVT",
      brakes: "Magura MT5 hydraulic disc",
      weight: "24.8 kg",
      wheelSize: "28\"",
      material: "Aluminum",
      motor: "Bosch Performance Line Speed 85Nm",
      battery: "Bosch PowerTube 380Wh",
      range: "Up to 100km",
      connectivity: "Bosch eBike Flow app"
    },
    stock: 4,
    isNew: true,
    isFeatured: true,
    tags: ["premium", "electric", "smart", "connected"],
    images: ["electric", "electric3", "electric2"]
  }
];

const REVIEWS = {
  1: [
    { id: 1, author: "Thomas B.", rating: 5, date: "2025-11-12", title: "Absolute beast on the road", text: "Been riding this for 3 months and it keeps getting better. The carbon frame absorbs road chatter like magic. Climbs are where it really shines — 7.4kg feels like flying uphill.", verified: true, helpful: 23 },
    { id: 2, author: "Mieke V.", rating: 5, date: "2025-10-03", title: "Worth every euro", text: "Upgraded from an aluminum bike and the difference is night and day. Ultegra groupset shifts flawlessly. My Strava segments have improved by 8% on average.", verified: true, helpful: 18 },
    { id: 3, author: "Lars K.", rating: 4, date: "2025-09-15", title: "Great bike, slightly harsh on cobbles", text: "Fantastic on smooth tarmac. A touch harsh on Belgian cobbles but that's the nature of a stiff race bike. Brakes are excellent in wet conditions.", verified: false, helpful: 7 }
  ],
  2: [
    { id: 1, author: "Femke D.", rating: 5, date: "2025-12-01", title: "Trail perfection", text: "The geometry is spot on. Confidently tore through some nasty technical sections at Veluwe that had me nervous before. The GX Eagle shifting is crisp and reliable.", verified: true, helpful: 31 },
    { id: 2, author: "Joris M.", rating: 5, date: "2025-11-20", title: "Best trail bike under €3000", text: "Tried 4 different trail bikes before landing on this. Nothing comes close for the price. Suspension feel is plush but doesn't bob on climbs.", verified: true, helpful: 19 }
  ],
  3: [
    { id: 1, author: "Anneke S.", rating: 5, date: "2025-10-28", title: "My daily driver for 2 years", text: "Rain or shine, this bike gets me to work fresh. The automatic gearing is a game-changer in city traffic. 130km range means I charge maybe once a week.", verified: true, helpful: 44 },
    { id: 2, author: "Peter W.", rating: 4, date: "2025-09-14", title: "Excellent but heavy", text: "The riding experience is smooth and the motor response is natural. Only knock is the weight — getting it up stairs is a workout in itself!", verified: true, helpful: 12 }
  ]
};

const BRANDS = [
  { name: "Trek", country: "USA", founded: 1976, logo: "🚴" },
  { name: "Specialized", country: "USA", founded: 1974, logo: "⚡" },
  { name: "Giant", country: "Taiwan", founded: 1972, logo: "🏔️" },
  { name: "Gazelle", country: "Netherlands", founded: 1892, logo: "🌷" },
  { name: "Batavus", country: "Netherlands", founded: 1904, logo: "🇳🇱" },
  { name: "Cannondale", country: "USA", founded: 1971, logo: "🔥" },
  { name: "Scott", country: "Switzerland", founded: 1958, logo: "🏔️" },
  { name: "Cube", country: "Germany", founded: 1993, logo: "🎯" }
];

const BLOG_POSTS = [
  {
    id: 1,
    title: "5 Reasons to Switch to an E-Bike in 2026",
    category: "Electric Bikes",
    date: "2026-06-15",
    author: "Sanne de Vries",
    excerpt: "Electric bikes have exploded in popularity, and for good reason. Here's why 2026 might be the year you finally make the switch — and which models are worth the investment.",
    readTime: "5 min",
    image: "electric"
  },
  {
    id: 2,
    title: "How to Choose Your First Mountain Bike",
    category: "Buying Guides",
    date: "2026-05-28",
    author: "Mark van den Berg",
    excerpt: "Trail riding is addictive once you start. But the mountain bike market can be overwhelming. Here's our no-nonsense guide to picking the right hardtail or full-sus for your needs.",
    readTime: "8 min",
    image: "mountain"
  },
  {
    id: 3,
    title: "Bike Maintenance 101: Keep Your Ride Running Smooth",
    category: "Maintenance",
    date: "2026-05-10",
    author: "Roos Bakker",
    excerpt: "A well-maintained bike is a safe, fast bike. Learn the essential maintenance routines that every cyclist should know — from chain lubing to brake bleeding.",
    readTime: "6 min",
    image: "road"
  }
];

const STORE_LOCATIONS = [
  { name: "VeloWorld Amsterdam", address: "Damrak 44, 1012 LK Amsterdam", phone: "+31 20 123 4567", hours: "Mon-Sat 9:00-18:00", coords: [52.3771, 4.9007] },
  { name: "VeloWorld Rotterdam", address: "Coolsingel 105, 3012 AG Rotterdam", phone: "+31 10 234 5678", hours: "Mon-Sat 9:00-18:00, Sun 11:00-17:00", coords: [51.9225, 4.4792] },
  { name: "VeloWorld Utrecht", address: "Oudegracht 112, 3511 AW Utrecht", phone: "+31 30 345 6789", hours: "Mon-Sat 9:00-18:00", coords: [52.0907, 5.1214] },
  { name: "VeloWorld Den Haag", address: "Spui 15, 2511 BJ Den Haag", phone: "+31 70 456 7890", hours: "Mon-Sat 9:00-17:30", coords: [52.0705, 4.3007] },
  { name: "VeloWorld Eindhoven", address: "18 Septemberplein 4, 5611 EK Eindhoven", phone: "+31 40 567 8901", hours: "Tue-Sat 9:00-18:00", coords: [51.4416, 5.4697] }
];

const FAQ_ITEMS = [
  { q: "Do you offer test rides?", a: "Yes! All our physical stores offer test rides on most models in our range. Simply visit your nearest VeloWorld store and our staff will set up a test bike matched to your size. No appointment needed during weekdays." },
  { q: "What's your return policy?", a: "We offer a 30-day return policy for unused bikes in original packaging. For bikes that have been ridden, we offer a 7-day satisfaction guarantee — if it doesn't feel right, bring it back and we'll find you something better." },
  { q: "Do you ship internationally?", a: "We ship to all EU countries. Bikes are professionally packed and insured during transit. Standard EU delivery takes 3-7 business days. Express 2-day shipping is available for an additional fee." },
  { q: "Is assembly required?", a: "Bikes are delivered 95% assembled. You'll only need to attach the front wheel, handlebars (if folded for shipping), and seat post. Full assembly instructions are included, and our support team is available via chat if you need help." },
  { q: "Do you offer financing?", a: "Yes! We partner with Klarna and Afterpay to offer flexible payment plans. Split your purchase into 3, 6, or 12 monthly installments with 0% interest on orders over €500." },
  { q: "How do I maintain my e-bike battery?", a: "Store your battery between 20-80% charge when not in use for extended periods. Avoid exposing it to extreme temperatures. Charge after every ride for daily use. With proper care, Bosch batteries retain 60% capacity after 500+ charge cycles." },
  { q: "What size bike do I need?", a: "Use our Size Calculator tool on any product page! Enter your height and inseam length and we'll recommend the perfect frame size. Generally: under 165cm → XS/S, 165-175cm → S/M, 175-185cm → M/L, over 185cm → L/XL." },
  { q: "Do you offer a warranty?", a: "All bikes come with the manufacturer's warranty (typically 2 years on frame, 1 year on components). We also offer extended VeloWorld Care plans for 3 or 5 years of coverage including annual services." }
];
